local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 5
   publish_frequency: 2
   width: 6.0
   height: 6.0
   resolution: 0.05
   static_map: false
   rolling_window: true
