map_type: costmap

obstacle_range: 4.0
raytrace_range: 4.0
transform_tolerance: 0.2
update_frequency: 10.0
publish_frequency: 5.0
inflation_radius: 0.6
xy_goal_tolerance: 0.05
yaw_goal_tolerance: 0.01
always_send_full_costmap: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /hsa_bot/laser/scan, marking: true, clearing: true}
